// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::auth_status_type::AuthStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Auth7702 {
    pub authority_address: String,
    pub chain_id: u64,
    pub delegate_to: String,
    pub nonce: u64,
    pub v: u8,
    pub r: String,
    pub s: String,
    pub status: AuthStatus,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Auth7702 {
    type Module = super::RemoteModule;
}
