// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::auth_7702_type::Auth7702;
use super::auth_status_type::AuthStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `auth_7702`.
///
/// Obtain a handle from the [`Auth7702TableAccess::auth_7702`] method on [`super::RemoteTables`],
/// like `ctx.db.auth_7702()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.auth_7702().on_insert(...)`.
pub struct Auth7702TableHandle<'ctx> {
    imp: __sdk::TableHandle<Auth7702>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `auth_7702`.
///
/// Implemented for [`super::RemoteTables`].
pub trait Auth7702TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`Auth7702TableHandle`], which mediates access to the table `auth_7702`.
    fn auth_7702(&self) -> Auth7702TableHandle<'_>;
}

impl Auth7702TableAccess for super::RemoteTables {
    fn auth_7702(&self) -> Auth7702TableHandle<'_> {
        Auth7702TableHandle {
            imp: self.imp.get_table::<Auth7702>("auth_7702"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct Auth7702InsertCallbackId(__sdk::CallbackId);
pub struct Auth7702DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for Auth7702TableHandle<'ctx> {
    type Row = Auth7702;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Auth7702> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = Auth7702InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Auth7702InsertCallbackId {
        Auth7702InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: Auth7702InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = Auth7702DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> Auth7702DeleteCallbackId {
        Auth7702DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: Auth7702DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Auth7702>("auth_7702");
    _table.add_unique_constraint::<String>("authority_address", |row| &row.authority_address);
}
pub struct Auth7702UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for Auth7702TableHandle<'ctx> {
    type UpdateCallbackId = Auth7702UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> Auth7702UpdateCallbackId {
        Auth7702UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: Auth7702UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Auth7702>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Auth7702>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `authority_address` unique index on the table `auth_7702`,
/// which allows point queries on the field of the same name
/// via the [`Auth7702AuthorityAddressUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.auth_7702().authority_address().find(...)`.
pub struct Auth7702AuthorityAddressUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Auth7702, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> Auth7702TableHandle<'ctx> {
    /// Get a handle on the `authority_address` unique index on the table `auth_7702`.
    pub fn authority_address(&self) -> Auth7702AuthorityAddressUnique<'ctx> {
        Auth7702AuthorityAddressUnique {
            imp: self
                .imp
                .get_unique_constraint::<String>("authority_address"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> Auth7702AuthorityAddressUnique<'ctx> {
    /// Find the subscribed row whose `authority_address` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Auth7702> {
        self.imp.find(col_val)
    }
}
