// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::balance_query_type::BalanceQuery;
use super::query_status_type::QueryStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `balance_query`.
///
/// Obtain a handle from the [`BalanceQueryTableAccess::balance_query`] method on [`super::RemoteTables`],
/// like `ctx.db.balance_query()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.balance_query().on_insert(...)`.
pub struct BalanceQueryTableHandle<'ctx> {
    imp: __sdk::TableHandle<BalanceQuery>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `balance_query`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BalanceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BalanceQueryTableHandle`], which mediates access to the table `balance_query`.
    fn balance_query(&self) -> BalanceQueryTableHandle<'_>;
}

impl BalanceQueryTableAccess for super::RemoteTables {
    fn balance_query(&self) -> BalanceQueryTableHandle<'_> {
        BalanceQueryTableHandle {
            imp: self.imp.get_table::<BalanceQuery>("balance_query"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BalanceQueryInsertCallbackId(__sdk::CallbackId);
pub struct BalanceQueryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BalanceQueryTableHandle<'ctx> {
    type Row = BalanceQuery;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BalanceQuery> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BalanceQueryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BalanceQueryInsertCallbackId {
        BalanceQueryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BalanceQueryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BalanceQueryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BalanceQueryDeleteCallbackId {
        BalanceQueryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BalanceQueryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BalanceQuery>("balance_query");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}
pub struct BalanceQueryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BalanceQueryTableHandle<'ctx> {
    type UpdateCallbackId = BalanceQueryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BalanceQueryUpdateCallbackId {
        BalanceQueryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BalanceQueryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BalanceQuery>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BalanceQuery>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `session_id` unique index on the table `balance_query`,
/// which allows point queries on the field of the same name
/// via the [`BalanceQuerySessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.balance_query().session_id().find(...)`.
pub struct BalanceQuerySessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BalanceQuery, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BalanceQueryTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `balance_query`.
    pub fn session_id(&self) -> BalanceQuerySessionIdUnique<'ctx> {
        BalanceQuerySessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BalanceQuerySessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<BalanceQuery> {
        self.imp.find(col_val)
    }
}
