// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimGatewayIdentityArgs {}

impl From<ClaimGatewayIdentityArgs> for super::Reducer {
    fn from(args: ClaimGatewayIdentityArgs) -> Self {
        Self::ClaimGatewayIdentity
    }
}

impl __sdk::InModule for ClaimGatewayIdentityArgs {
    type Module = super::RemoteModule;
}

pub struct ClaimGatewayIdentityCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_gateway_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_gateway_identity {
    /// Request that the remote module invoke the reducer `claim_gateway_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_claim_gateway_identity`] callbacks.
    fn claim_gateway_identity(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `claim_gateway_identity`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClaimGatewayIdentityCallbackId`] can be passed to [`Self::remove_on_claim_gateway_identity`]
    /// to cancel the callback.
    fn on_claim_gateway_identity(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClaimGatewayIdentityCallbackId;
    /// Cancel a callback previously registered by [`Self::on_claim_gateway_identity`],
    /// causing it not to run in the future.
    fn remove_on_claim_gateway_identity(&self, callback: ClaimGatewayIdentityCallbackId);
}

impl claim_gateway_identity for super::RemoteReducers {
    fn claim_gateway_identity(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("claim_gateway_identity", ClaimGatewayIdentityArgs {})
    }
    fn on_claim_gateway_identity(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClaimGatewayIdentityCallbackId {
        ClaimGatewayIdentityCallbackId(self.imp.on_reducer(
            "claim_gateway_identity",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClaimGatewayIdentity {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_claim_gateway_identity(&self, callback: ClaimGatewayIdentityCallbackId) {
        self.imp
            .remove_on_reducer("claim_gateway_identity", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `claim_gateway_identity`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_claim_gateway_identity {
    /// Set the call-reducer flags for the reducer `claim_gateway_identity` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn claim_gateway_identity(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_claim_gateway_identity for super::SetReducerFlags {
    fn claim_gateway_identity(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("claim_gateway_identity", flags);
    }
}
