// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConfirmEthTxArgs {
    pub eth_tx_id: u64,
    pub tx_hash: String,
    pub block_number: u64,
    pub gas_used: String,
}

impl From<ConfirmEthTxArgs> for super::Reducer {
    fn from(args: ConfirmEthTxArgs) -> Self {
        Self::ConfirmEthTx {
            eth_tx_id: args.eth_tx_id,
            tx_hash: args.tx_hash,
            block_number: args.block_number,
            gas_used: args.gas_used,
        }
    }
}

impl __sdk::InModule for ConfirmEthTxArgs {
    type Module = super::RemoteModule;
}

pub struct ConfirmEthTxCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `confirm_eth_tx`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait confirm_eth_tx {
    /// Request that the remote module invoke the reducer `confirm_eth_tx` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_confirm_eth_tx`] callbacks.
    fn confirm_eth_tx(
        &self,
        eth_tx_id: u64,
        tx_hash: String,
        block_number: u64,
        gas_used: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `confirm_eth_tx`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ConfirmEthTxCallbackId`] can be passed to [`Self::remove_on_confirm_eth_tx`]
    /// to cancel the callback.
    fn on_confirm_eth_tx(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &u64, &String) + Send + 'static,
    ) -> ConfirmEthTxCallbackId;
    /// Cancel a callback previously registered by [`Self::on_confirm_eth_tx`],
    /// causing it not to run in the future.
    fn remove_on_confirm_eth_tx(&self, callback: ConfirmEthTxCallbackId);
}

impl confirm_eth_tx for super::RemoteReducers {
    fn confirm_eth_tx(
        &self,
        eth_tx_id: u64,
        tx_hash: String,
        block_number: u64,
        gas_used: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "confirm_eth_tx",
            ConfirmEthTxArgs {
                eth_tx_id,
                tx_hash,
                block_number,
                gas_used,
            },
        )
    }
    fn on_confirm_eth_tx(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &u64, &String)
            + Send
            + 'static,
    ) -> ConfirmEthTxCallbackId {
        ConfirmEthTxCallbackId(self.imp.on_reducer(
            "confirm_eth_tx",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ConfirmEthTx {
                                    eth_tx_id,
                                    tx_hash,
                                    block_number,
                                    gas_used,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, eth_tx_id, tx_hash, block_number, gas_used)
            }),
        ))
    }
    fn remove_on_confirm_eth_tx(&self, callback: ConfirmEthTxCallbackId) {
        self.imp.remove_on_reducer("confirm_eth_tx", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `confirm_eth_tx`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_confirm_eth_tx {
    /// Set the call-reducer flags for the reducer `confirm_eth_tx` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn confirm_eth_tx(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_confirm_eth_tx for super::SetReducerFlags {
    fn confirm_eth_tx(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("confirm_eth_tx", flags);
    }
}
