// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::esim_profile_type::EsimProfile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `esim_profile`.
///
/// Obtain a handle from the [`EsimProfileTableAccess::esim_profile`] method on [`super::RemoteTables`],
/// like `ctx.db.esim_profile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.esim_profile().on_insert(...)`.
pub struct EsimProfileTableHandle<'ctx> {
    imp: __sdk::TableHandle<EsimProfile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `esim_profile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EsimProfileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EsimProfileTableHandle`], which mediates access to the table `esim_profile`.
    fn esim_profile(&self) -> EsimProfileTableHandle<'_>;
}

impl EsimProfileTableAccess for super::RemoteTables {
    fn esim_profile(&self) -> EsimProfileTableHandle<'_> {
        EsimProfileTableHandle {
            imp: self.imp.get_table::<EsimProfile>("esim_profile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EsimProfileInsertCallbackId(__sdk::CallbackId);
pub struct EsimProfileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EsimProfileTableHandle<'ctx> {
    type Row = EsimProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EsimProfile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EsimProfileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EsimProfileInsertCallbackId {
        EsimProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EsimProfileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EsimProfileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EsimProfileDeleteCallbackId {
        EsimProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EsimProfileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EsimProfile>("esim_profile");
    _table.add_unique_constraint::<String>("phone_number", |row| &row.phone_number);
}
pub struct EsimProfileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EsimProfileTableHandle<'ctx> {
    type UpdateCallbackId = EsimProfileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EsimProfileUpdateCallbackId {
        EsimProfileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EsimProfileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<EsimProfile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EsimProfile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `phone_number` unique index on the table `esim_profile`,
/// which allows point queries on the field of the same name
/// via the [`EsimProfilePhoneNumberUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.esim_profile().phone_number().find(...)`.
pub struct EsimProfilePhoneNumberUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EsimProfile, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EsimProfileTableHandle<'ctx> {
    /// Get a handle on the `phone_number` unique index on the table `esim_profile`.
    pub fn phone_number(&self) -> EsimProfilePhoneNumberUnique<'ctx> {
        EsimProfilePhoneNumberUnique {
            imp: self.imp.get_unique_constraint::<String>("phone_number"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EsimProfilePhoneNumberUnique<'ctx> {
    /// Find the subscribed row whose `phone_number` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<EsimProfile> {
        self.imp.find(col_val)
    }
}
