// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::eth_audit_log_type::EthAuditLog;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `eth_audit_logs`.
///
/// Obtain a handle from the [`EthAuditLogsTableAccess::eth_audit_logs`] method on [`super::RemoteTables`],
/// like `ctx.db.eth_audit_logs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.eth_audit_logs().on_insert(...)`.
pub struct EthAuditLogsTableHandle<'ctx> {
    imp: __sdk::TableHandle<EthAuditLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `eth_audit_logs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EthAuditLogsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EthAuditLogsTableHandle`], which mediates access to the table `eth_audit_logs`.
    fn eth_audit_logs(&self) -> EthAuditLogsTableHandle<'_>;
}

impl EthAuditLogsTableAccess for super::RemoteTables {
    fn eth_audit_logs(&self) -> EthAuditLogsTableHandle<'_> {
        EthAuditLogsTableHandle {
            imp: self.imp.get_table::<EthAuditLog>("eth_audit_logs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EthAuditLogsInsertCallbackId(__sdk::CallbackId);
pub struct EthAuditLogsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EthAuditLogsTableHandle<'ctx> {
    type Row = EthAuditLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EthAuditLog> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EthAuditLogsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EthAuditLogsInsertCallbackId {
        EthAuditLogsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EthAuditLogsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EthAuditLogsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EthAuditLogsDeleteCallbackId {
        EthAuditLogsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EthAuditLogsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EthAuditLog>("eth_audit_logs");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct EthAuditLogsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EthAuditLogsTableHandle<'ctx> {
    type UpdateCallbackId = EthAuditLogsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EthAuditLogsUpdateCallbackId {
        EthAuditLogsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EthAuditLogsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<EthAuditLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EthAuditLog>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `eth_audit_logs`,
/// which allows point queries on the field of the same name
/// via the [`EthAuditLogsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.eth_audit_logs().id().find(...)`.
pub struct EthAuditLogsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EthAuditLog, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EthAuditLogsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `eth_audit_logs`.
    pub fn id(&self) -> EthAuditLogsIdUnique<'ctx> {
        EthAuditLogsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EthAuditLogsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EthAuditLog> {
        self.imp.find(col_val)
    }
}
