// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::tx_status_type::TxStatus;
use super::tx_type_type::TxType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EthTx {
    pub id: u64,
    pub session_id: String,
    pub tx_type: TxType,
    pub from: String,
    pub to: String,
    pub value: String,
    pub data: Option<Vec<u8>>,
    pub gas_limit: String,
    pub status: TxStatus,
    pub tx_hash: Option<String>,
    pub block_number: Option<u64>,
    pub gas_used: Option<String>,
    pub error_reason: Option<String>,
    pub processing_by: Option<String>,
    pub processing_since: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for EthTx {
    type Module = super::RemoteModule;
}
