// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FailEthTxArgs {
    pub eth_tx_id: u64,
    pub tx_hash: Option<String>,
    pub reason: String,
}

impl From<FailEthTxArgs> for super::Reducer {
    fn from(args: FailEthTxArgs) -> Self {
        Self::FailEthTx {
            eth_tx_id: args.eth_tx_id,
            tx_hash: args.tx_hash,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for FailEthTxArgs {
    type Module = super::RemoteModule;
}

pub struct FailEthTxCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fail_eth_tx`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fail_eth_tx {
    /// Request that the remote module invoke the reducer `fail_eth_tx` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_fail_eth_tx`] callbacks.
    fn fail_eth_tx(
        &self,
        eth_tx_id: u64,
        tx_hash: Option<String>,
        reason: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `fail_eth_tx`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`FailEthTxCallbackId`] can be passed to [`Self::remove_on_fail_eth_tx`]
    /// to cancel the callback.
    fn on_fail_eth_tx(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &Option<String>, &String)
            + Send
            + 'static,
    ) -> FailEthTxCallbackId;
    /// Cancel a callback previously registered by [`Self::on_fail_eth_tx`],
    /// causing it not to run in the future.
    fn remove_on_fail_eth_tx(&self, callback: FailEthTxCallbackId);
}

impl fail_eth_tx for super::RemoteReducers {
    fn fail_eth_tx(
        &self,
        eth_tx_id: u64,
        tx_hash: Option<String>,
        reason: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "fail_eth_tx",
            FailEthTxArgs {
                eth_tx_id,
                tx_hash,
                reason,
            },
        )
    }
    fn on_fail_eth_tx(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &Option<String>, &String)
            + Send
            + 'static,
    ) -> FailEthTxCallbackId {
        FailEthTxCallbackId(self.imp.on_reducer(
            "fail_eth_tx",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::FailEthTx {
                                    eth_tx_id,
                                    tx_hash,
                                    reason,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, eth_tx_id, tx_hash, reason)
            }),
        ))
    }
    fn remove_on_fail_eth_tx(&self, callback: FailEthTxCallbackId) {
        self.imp.remove_on_reducer("fail_eth_tx", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `fail_eth_tx`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_fail_eth_tx {
    /// Set the call-reducer flags for the reducer `fail_eth_tx` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn fail_eth_tx(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_fail_eth_tx for super::SetReducerFlags {
    fn fail_eth_tx(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("fail_eth_tx", flags);
    }
}
