// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LogSendEthTransactionArgs {
    pub tx_hash: String,
    pub from_address: String,
    pub to_address: String,
    pub amount: String,
    pub phone_number: String,
    pub session_id: String,
}

impl From<LogSendEthTransactionArgs> for super::Reducer {
    fn from(args: LogSendEthTransactionArgs) -> Self {
        Self::LogSendEthTransaction {
            tx_hash: args.tx_hash,
            from_address: args.from_address,
            to_address: args.to_address,
            amount: args.amount,
            phone_number: args.phone_number,
            session_id: args.session_id,
        }
    }
}

impl __sdk::InModule for LogSendEthTransactionArgs {
    type Module = super::RemoteModule;
}

pub struct LogSendEthTransactionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `log_send_eth_transaction`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait log_send_eth_transaction {
    /// Request that the remote module invoke the reducer `log_send_eth_transaction` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_log_send_eth_transaction`] callbacks.
    fn log_send_eth_transaction(
        &self,
        tx_hash: String,
        from_address: String,
        to_address: String,
        amount: String,
        phone_number: String,
        session_id: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `log_send_eth_transaction`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`LogSendEthTransactionCallbackId`] can be passed to [`Self::remove_on_log_send_eth_transaction`]
    /// to cancel the callback.
    fn on_log_send_eth_transaction(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &String, &String)
            + Send
            + 'static,
    ) -> LogSendEthTransactionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_log_send_eth_transaction`],
    /// causing it not to run in the future.
    fn remove_on_log_send_eth_transaction(&self, callback: LogSendEthTransactionCallbackId);
}

impl log_send_eth_transaction for super::RemoteReducers {
    fn log_send_eth_transaction(
        &self,
        tx_hash: String,
        from_address: String,
        to_address: String,
        amount: String,
        phone_number: String,
        session_id: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "log_send_eth_transaction",
            LogSendEthTransactionArgs {
                tx_hash,
                from_address,
                to_address,
                amount,
                phone_number,
                session_id,
            },
        )
    }
    fn on_log_send_eth_transaction(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &String, &String)
            + Send
            + 'static,
    ) -> LogSendEthTransactionCallbackId {
        LogSendEthTransactionCallbackId(self.imp.on_reducer(
            "log_send_eth_transaction",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::LogSendEthTransaction {
                                    tx_hash,
                                    from_address,
                                    to_address,
                                    amount,
                                    phone_number,
                                    session_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    tx_hash,
                    from_address,
                    to_address,
                    amount,
                    phone_number,
                    session_id,
                )
            }),
        ))
    }
    fn remove_on_log_send_eth_transaction(&self, callback: LogSendEthTransactionCallbackId) {
        self.imp
            .remove_on_reducer("log_send_eth_transaction", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `log_send_eth_transaction`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_log_send_eth_transaction {
    /// Set the call-reducer flags for the reducer `log_send_eth_transaction` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn log_send_eth_transaction(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_log_send_eth_transaction for super::SetReducerFlags {
    fn log_send_eth_transaction(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("log_send_eth_transaction", flags);
    }
}
