// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LogSendEthTransactionWithFatfArgs {
    pub tx_hash: String,
    pub from_address: String,
    pub to_address: String,
    pub amount: String,
    pub phone_number: String,
    pub session_id: String,
    pub originator_name: Option<String>,
    pub beneficiary_name: Option<String>,
    pub originator_country: Option<String>,
    pub beneficiary_country: Option<String>,
    pub originator_address: Option<String>,
    pub beneficiary_address: Option<String>,
    pub gas_fee: Option<String>,
    pub exchange_rate: Option<String>,
}

impl From<LogSendEthTransactionWithFatfArgs> for super::Reducer {
    fn from(args: LogSendEthTransactionWithFatfArgs) -> Self {
        Self::LogSendEthTransactionWithFatf {
            tx_hash: args.tx_hash,
            from_address: args.from_address,
            to_address: args.to_address,
            amount: args.amount,
            phone_number: args.phone_number,
            session_id: args.session_id,
            originator_name: args.originator_name,
            beneficiary_name: args.beneficiary_name,
            originator_country: args.originator_country,
            beneficiary_country: args.beneficiary_country,
            originator_address: args.originator_address,
            beneficiary_address: args.beneficiary_address,
            gas_fee: args.gas_fee,
            exchange_rate: args.exchange_rate,
        }
    }
}

impl __sdk::InModule for LogSendEthTransactionWithFatfArgs {
    type Module = super::RemoteModule;
}

pub struct LogSendEthTransactionWithFatfCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `log_send_eth_transaction_with_fatf`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait log_send_eth_transaction_with_fatf {
    /// Request that the remote module invoke the reducer `log_send_eth_transaction_with_fatf` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_log_send_eth_transaction_with_fatf`] callbacks.
    fn log_send_eth_transaction_with_fatf(
        &self,
        tx_hash: String,
        from_address: String,
        to_address: String,
        amount: String,
        phone_number: String,
        session_id: String,
        originator_name: Option<String>,
        beneficiary_name: Option<String>,
        originator_country: Option<String>,
        beneficiary_country: Option<String>,
        originator_address: Option<String>,
        beneficiary_address: Option<String>,
        gas_fee: Option<String>,
        exchange_rate: Option<String>,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `log_send_eth_transaction_with_fatf`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`LogSendEthTransactionWithFatfCallbackId`] can be passed to [`Self::remove_on_log_send_eth_transaction_with_fatf`]
    /// to cancel the callback.
    fn on_log_send_eth_transaction_with_fatf(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
                &String,
                &String,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
            ) + Send
            + 'static,
    ) -> LogSendEthTransactionWithFatfCallbackId;
    /// Cancel a callback previously registered by [`Self::on_log_send_eth_transaction_with_fatf`],
    /// causing it not to run in the future.
    fn remove_on_log_send_eth_transaction_with_fatf(
        &self,
        callback: LogSendEthTransactionWithFatfCallbackId,
    );
}

impl log_send_eth_transaction_with_fatf for super::RemoteReducers {
    fn log_send_eth_transaction_with_fatf(
        &self,
        tx_hash: String,
        from_address: String,
        to_address: String,
        amount: String,
        phone_number: String,
        session_id: String,
        originator_name: Option<String>,
        beneficiary_name: Option<String>,
        originator_country: Option<String>,
        beneficiary_country: Option<String>,
        originator_address: Option<String>,
        beneficiary_address: Option<String>,
        gas_fee: Option<String>,
        exchange_rate: Option<String>,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "log_send_eth_transaction_with_fatf",
            LogSendEthTransactionWithFatfArgs {
                tx_hash,
                from_address,
                to_address,
                amount,
                phone_number,
                session_id,
                originator_name,
                beneficiary_name,
                originator_country,
                beneficiary_country,
                originator_address,
                beneficiary_address,
                gas_fee,
                exchange_rate,
            },
        )
    }
    fn on_log_send_eth_transaction_with_fatf(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
                &String,
                &String,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
                &Option<String>,
            ) + Send
            + 'static,
    ) -> LogSendEthTransactionWithFatfCallbackId {
        LogSendEthTransactionWithFatfCallbackId(self.imp.on_reducer(
            "log_send_eth_transaction_with_fatf",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::LogSendEthTransactionWithFatf {
                                    tx_hash,
                                    from_address,
                                    to_address,
                                    amount,
                                    phone_number,
                                    session_id,
                                    originator_name,
                                    beneficiary_name,
                                    originator_country,
                                    beneficiary_country,
                                    originator_address,
                                    beneficiary_address,
                                    gas_fee,
                                    exchange_rate,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    tx_hash,
                    from_address,
                    to_address,
                    amount,
                    phone_number,
                    session_id,
                    originator_name,
                    beneficiary_name,
                    originator_country,
                    beneficiary_country,
                    originator_address,
                    beneficiary_address,
                    gas_fee,
                    exchange_rate,
                )
            }),
        ))
    }
    fn remove_on_log_send_eth_transaction_with_fatf(
        &self,
        callback: LogSendEthTransactionWithFatfCallbackId,
    ) {
        self.imp
            .remove_on_reducer("log_send_eth_transaction_with_fatf", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `log_send_eth_transaction_with_fatf`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_log_send_eth_transaction_with_fatf {
    /// Set the call-reducer flags for the reducer `log_send_eth_transaction_with_fatf` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn log_send_eth_transaction_with_fatf(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_log_send_eth_transaction_with_fatf for super::SetReducerFlags {
    fn log_send_eth_transaction_with_fatf(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("log_send_eth_transaction_with_fatf", flags);
    }
}
