// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MapPhoneToWalletArgs {
    pub phone_number: String,
    pub wallet_address: String,
    pub chain_id: u64,
    pub delegate_to: String,
    pub nonce: u64,
    pub v: u64,
    pub r: String,
    pub s: String,
}

impl From<MapPhoneToWalletArgs> for super::Reducer {
    fn from(args: MapPhoneToWalletArgs) -> Self {
        Self::MapPhoneToWallet {
            phone_number: args.phone_number,
            wallet_address: args.wallet_address,
            chain_id: args.chain_id,
            delegate_to: args.delegate_to,
            nonce: args.nonce,
            v: args.v,
            r: args.r,
            s: args.s,
        }
    }
}

impl __sdk::InModule for MapPhoneToWalletArgs {
    type Module = super::RemoteModule;
}

pub struct MapPhoneToWalletCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `map_phone_to_wallet`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait map_phone_to_wallet {
    /// Request that the remote module invoke the reducer `map_phone_to_wallet` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_map_phone_to_wallet`] callbacks.
    fn map_phone_to_wallet(
        &self,
        phone_number: String,
        wallet_address: String,
        chain_id: u64,
        delegate_to: String,
        nonce: u64,
        v: u64,
        r: String,
        s: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `map_phone_to_wallet`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MapPhoneToWalletCallbackId`] can be passed to [`Self::remove_on_map_phone_to_wallet`]
    /// to cancel the callback.
    fn on_map_phone_to_wallet(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &u64,
                &String,
                &u64,
                &u64,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> MapPhoneToWalletCallbackId;
    /// Cancel a callback previously registered by [`Self::on_map_phone_to_wallet`],
    /// causing it not to run in the future.
    fn remove_on_map_phone_to_wallet(&self, callback: MapPhoneToWalletCallbackId);
}

impl map_phone_to_wallet for super::RemoteReducers {
    fn map_phone_to_wallet(
        &self,
        phone_number: String,
        wallet_address: String,
        chain_id: u64,
        delegate_to: String,
        nonce: u64,
        v: u64,
        r: String,
        s: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "map_phone_to_wallet",
            MapPhoneToWalletArgs {
                phone_number,
                wallet_address,
                chain_id,
                delegate_to,
                nonce,
                v,
                r,
                s,
            },
        )
    }
    fn on_map_phone_to_wallet(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &u64,
                &String,
                &u64,
                &u64,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> MapPhoneToWalletCallbackId {
        MapPhoneToWalletCallbackId(self.imp.on_reducer(
            "map_phone_to_wallet",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::MapPhoneToWallet {
                                    phone_number,
                                    wallet_address,
                                    chain_id,
                                    delegate_to,
                                    nonce,
                                    v,
                                    r,
                                    s,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    phone_number,
                    wallet_address,
                    chain_id,
                    delegate_to,
                    nonce,
                    v,
                    r,
                    s,
                )
            }),
        ))
    }
    fn remove_on_map_phone_to_wallet(&self, callback: MapPhoneToWalletCallbackId) {
        self.imp
            .remove_on_reducer("map_phone_to_wallet", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `map_phone_to_wallet`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_map_phone_to_wallet {
    /// Set the call-reducer flags for the reducer `map_phone_to_wallet` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn map_phone_to_wallet(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_map_phone_to_wallet for super::SetReducerFlags {
    fn map_phone_to_wallet(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("map_phone_to_wallet", flags);
    }
}
