// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkAuth7702ActiveArgs {
    pub authority_address: String,
}

impl From<MarkAuth7702ActiveArgs> for super::Reducer {
    fn from(args: MarkAuth7702ActiveArgs) -> Self {
        Self::MarkAuth7702Active {
            authority_address: args.authority_address,
        }
    }
}

impl __sdk::InModule for MarkAuth7702ActiveArgs {
    type Module = super::RemoteModule;
}

pub struct MarkAuth7702ActiveCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_auth7702_active`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_auth_7702_active {
    /// Request that the remote module invoke the reducer `mark_auth7702_active` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_mark_auth_7702_active`] callbacks.
    fn mark_auth_7702_active(&self, authority_address: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `mark_auth7702_active`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MarkAuth7702ActiveCallbackId`] can be passed to [`Self::remove_on_mark_auth_7702_active`]
    /// to cancel the callback.
    fn on_mark_auth_7702_active(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> MarkAuth7702ActiveCallbackId;
    /// Cancel a callback previously registered by [`Self::on_mark_auth_7702_active`],
    /// causing it not to run in the future.
    fn remove_on_mark_auth_7702_active(&self, callback: MarkAuth7702ActiveCallbackId);
}

impl mark_auth_7702_active for super::RemoteReducers {
    fn mark_auth_7702_active(&self, authority_address: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "mark_auth7702_active",
            MarkAuth7702ActiveArgs { authority_address },
        )
    }
    fn on_mark_auth_7702_active(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> MarkAuth7702ActiveCallbackId {
        MarkAuth7702ActiveCallbackId(self.imp.on_reducer(
            "mark_auth7702_active",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MarkAuth7702Active { authority_address },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, authority_address)
            }),
        ))
    }
    fn remove_on_mark_auth_7702_active(&self, callback: MarkAuth7702ActiveCallbackId) {
        self.imp
            .remove_on_reducer("mark_auth7702_active", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `mark_auth7702_active`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_mark_auth_7702_active {
    /// Set the call-reducer flags for the reducer `mark_auth7702_active` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn mark_auth_7702_active(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_mark_auth_7702_active for super::SetReducerFlags {
    fn mark_auth_7702_active(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("mark_auth7702_active", flags);
    }
}
