// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkEthTxBroadcastArgs {
    pub eth_tx_id: u64,
    pub tx_hash: String,
}

impl From<MarkEthTxBroadcastArgs> for super::Reducer {
    fn from(args: MarkEthTxBroadcastArgs) -> Self {
        Self::MarkEthTxBroadcast {
            eth_tx_id: args.eth_tx_id,
            tx_hash: args.tx_hash,
        }
    }
}

impl __sdk::InModule for MarkEthTxBroadcastArgs {
    type Module = super::RemoteModule;
}

pub struct MarkEthTxBroadcastCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_eth_tx_broadcast`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_eth_tx_broadcast {
    /// Request that the remote module invoke the reducer `mark_eth_tx_broadcast` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_mark_eth_tx_broadcast`] callbacks.
    fn mark_eth_tx_broadcast(&self, eth_tx_id: u64, tx_hash: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `mark_eth_tx_broadcast`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MarkEthTxBroadcastCallbackId`] can be passed to [`Self::remove_on_mark_eth_tx_broadcast`]
    /// to cancel the callback.
    fn on_mark_eth_tx_broadcast(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> MarkEthTxBroadcastCallbackId;
    /// Cancel a callback previously registered by [`Self::on_mark_eth_tx_broadcast`],
    /// causing it not to run in the future.
    fn remove_on_mark_eth_tx_broadcast(&self, callback: MarkEthTxBroadcastCallbackId);
}

impl mark_eth_tx_broadcast for super::RemoteReducers {
    fn mark_eth_tx_broadcast(&self, eth_tx_id: u64, tx_hash: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "mark_eth_tx_broadcast",
            MarkEthTxBroadcastArgs { eth_tx_id, tx_hash },
        )
    }
    fn on_mark_eth_tx_broadcast(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> MarkEthTxBroadcastCallbackId {
        MarkEthTxBroadcastCallbackId(self.imp.on_reducer(
            "mark_eth_tx_broadcast",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MarkEthTxBroadcast { eth_tx_id, tx_hash },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, eth_tx_id, tx_hash)
            }),
        ))
    }
    fn remove_on_mark_eth_tx_broadcast(&self, callback: MarkEthTxBroadcastCallbackId) {
        self.imp
            .remove_on_reducer("mark_eth_tx_broadcast", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `mark_eth_tx_broadcast`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_mark_eth_tx_broadcast {
    /// Set the call-reducer flags for the reducer `mark_eth_tx_broadcast` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn mark_eth_tx_broadcast(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_mark_eth_tx_broadcast for super::SetReducerFlags {
    fn mark_eth_tx_broadcast(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("mark_eth_tx_broadcast", flags);
    }
}
