// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkEthTxProcessingArgs {
    pub eth_tx_id: u64,
    pub worker_id: String,
}

impl From<MarkEthTxProcessingArgs> for super::Reducer {
    fn from(args: MarkEthTxProcessingArgs) -> Self {
        Self::MarkEthTxProcessing {
            eth_tx_id: args.eth_tx_id,
            worker_id: args.worker_id,
        }
    }
}

impl __sdk::InModule for MarkEthTxProcessingArgs {
    type Module = super::RemoteModule;
}

pub struct MarkEthTxProcessingCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_eth_tx_processing`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_eth_tx_processing {
    /// Request that the remote module invoke the reducer `mark_eth_tx_processing` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_mark_eth_tx_processing`] callbacks.
    fn mark_eth_tx_processing(&self, eth_tx_id: u64, worker_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `mark_eth_tx_processing`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MarkEthTxProcessingCallbackId`] can be passed to [`Self::remove_on_mark_eth_tx_processing`]
    /// to cancel the callback.
    fn on_mark_eth_tx_processing(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> MarkEthTxProcessingCallbackId;
    /// Cancel a callback previously registered by [`Self::on_mark_eth_tx_processing`],
    /// causing it not to run in the future.
    fn remove_on_mark_eth_tx_processing(&self, callback: MarkEthTxProcessingCallbackId);
}

impl mark_eth_tx_processing for super::RemoteReducers {
    fn mark_eth_tx_processing(&self, eth_tx_id: u64, worker_id: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "mark_eth_tx_processing",
            MarkEthTxProcessingArgs {
                eth_tx_id,
                worker_id,
            },
        )
    }
    fn on_mark_eth_tx_processing(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> MarkEthTxProcessingCallbackId {
        MarkEthTxProcessingCallbackId(self.imp.on_reducer(
            "mark_eth_tx_processing",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::MarkEthTxProcessing {
                                    eth_tx_id,
                                    worker_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, eth_tx_id, worker_id)
            }),
        ))
    }
    fn remove_on_mark_eth_tx_processing(&self, callback: MarkEthTxProcessingCallbackId) {
        self.imp
            .remove_on_reducer("mark_eth_tx_processing", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `mark_eth_tx_processing`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_mark_eth_tx_processing {
    /// Set the call-reducer flags for the reducer `mark_eth_tx_processing` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn mark_eth_tx_processing(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_mark_eth_tx_processing for super::SetReducerFlags {
    fn mark_eth_tx_processing(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("mark_eth_tx_processing", flags);
    }
}
