// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ussd_menu_item_type::UssdMenuItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `menu_item`.
///
/// Obtain a handle from the [`MenuItemTableAccess::menu_item`] method on [`super::RemoteTables`],
/// like `ctx.db.menu_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.menu_item().on_insert(...)`.
pub struct MenuItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdMenuItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `menu_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MenuItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MenuItemTableHandle`], which mediates access to the table `menu_item`.
    fn menu_item(&self) -> MenuItemTableHandle<'_>;
}

impl MenuItemTableAccess for super::RemoteTables {
    fn menu_item(&self) -> MenuItemTableHandle<'_> {
        MenuItemTableHandle {
            imp: self.imp.get_table::<UssdMenuItem>("menu_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MenuItemInsertCallbackId(__sdk::CallbackId);
pub struct MenuItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MenuItemTableHandle<'ctx> {
    type Row = UssdMenuItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdMenuItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MenuItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MenuItemInsertCallbackId {
        MenuItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MenuItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MenuItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MenuItemDeleteCallbackId {
        MenuItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MenuItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdMenuItem>("menu_item");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdMenuItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdMenuItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
