// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.1 (commit bbfa851b45db7096aa2a69d7dbad84f52983559f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod app_config_table;
pub mod app_config_type;
pub mod auth_7702_table;
pub mod auth_7702_type;
pub mod auth_status_type;
pub mod balance_query_table;
pub mod balance_query_type;
pub mod claim_gateway_identity_reducer;
pub mod confirm_eth_tx_reducer;
pub mod esim_profile_table;
pub mod esim_profile_type;
pub mod eth_audit_log_type;
pub mod eth_audit_logs_table;
pub mod eth_tx_table;
pub mod eth_tx_type;
pub mod fail_eth_tx_reducer;
pub mod identity_connected_reducer;
pub mod identity_disconnected_reducer;
pub mod log_send_eth_transaction_reducer;
pub mod log_send_eth_transaction_with_fatf_reducer;
pub mod map_phone_to_wallet_reducer;
pub mod mark_auth_7702_active_reducer;
pub mod mark_eth_tx_broadcast_reducer;
pub mod mark_eth_tx_processing_reducer;
pub mod menu_item_table;
pub mod process_ussd_step_reducer;
pub mod query_status_type;
pub mod router_option_table;
pub mod screen_type_type;
pub mod sms_notification_table;
pub mod sms_notification_type;
pub mod sms_status_type;
pub mod sms_template_type;
pub mod tx_status_type;
pub mod tx_type_type;
pub mod user_key_table;
pub mod user_key_type;
pub mod user_pin_table;
pub mod user_pin_type;
pub mod user_preferences_table;
pub mod user_preferences_type;
pub mod ussd_code_table;
pub mod ussd_code_type;
pub mod ussd_menu_item_type;
pub mod ussd_request_table;
pub mod ussd_request_type;
pub mod ussd_response_table;
pub mod ussd_response_type;
pub mod ussd_router_option_type;
pub mod ussd_screen_table;
pub mod ussd_screen_type;
pub mod ussd_service_table;
pub mod ussd_service_type;
pub mod ussd_session_table;
pub mod ussd_session_type;
pub mod withdrawal_request_table;
pub mod withdrawal_request_type;
pub mod withdrawal_status_type;

pub use app_config_table::*;
pub use app_config_type::AppConfig;
pub use auth_7702_table::*;
pub use auth_7702_type::Auth7702;
pub use auth_status_type::AuthStatus;
pub use balance_query_table::*;
pub use balance_query_type::BalanceQuery;
pub use claim_gateway_identity_reducer::{
    claim_gateway_identity, set_flags_for_claim_gateway_identity, ClaimGatewayIdentityCallbackId,
};
pub use confirm_eth_tx_reducer::{
    confirm_eth_tx, set_flags_for_confirm_eth_tx, ConfirmEthTxCallbackId,
};
pub use esim_profile_table::*;
pub use esim_profile_type::EsimProfile;
pub use eth_audit_log_type::EthAuditLog;
pub use eth_audit_logs_table::*;
pub use eth_tx_table::*;
pub use eth_tx_type::EthTx;
pub use fail_eth_tx_reducer::{fail_eth_tx, set_flags_for_fail_eth_tx, FailEthTxCallbackId};
pub use identity_connected_reducer::{
    identity_connected, set_flags_for_identity_connected, IdentityConnectedCallbackId,
};
pub use identity_disconnected_reducer::{
    identity_disconnected, set_flags_for_identity_disconnected, IdentityDisconnectedCallbackId,
};
pub use log_send_eth_transaction_reducer::{
    log_send_eth_transaction, set_flags_for_log_send_eth_transaction,
    LogSendEthTransactionCallbackId,
};
pub use log_send_eth_transaction_with_fatf_reducer::{
    log_send_eth_transaction_with_fatf, set_flags_for_log_send_eth_transaction_with_fatf,
    LogSendEthTransactionWithFatfCallbackId,
};
pub use map_phone_to_wallet_reducer::{
    map_phone_to_wallet, set_flags_for_map_phone_to_wallet, MapPhoneToWalletCallbackId,
};
pub use mark_auth_7702_active_reducer::{
    mark_auth_7702_active, set_flags_for_mark_auth_7702_active, MarkAuth7702ActiveCallbackId,
};
pub use mark_eth_tx_broadcast_reducer::{
    mark_eth_tx_broadcast, set_flags_for_mark_eth_tx_broadcast, MarkEthTxBroadcastCallbackId,
};
pub use mark_eth_tx_processing_reducer::{
    mark_eth_tx_processing, set_flags_for_mark_eth_tx_processing, MarkEthTxProcessingCallbackId,
};
pub use menu_item_table::*;
pub use process_ussd_step_reducer::{
    process_ussd_step, set_flags_for_process_ussd_step, ProcessUssdStepCallbackId,
};
pub use query_status_type::QueryStatus;
pub use router_option_table::*;
pub use screen_type_type::ScreenType;
pub use sms_notification_table::*;
pub use sms_notification_type::SmsNotification;
pub use sms_status_type::SmsStatus;
pub use sms_template_type::SmsTemplate;
pub use tx_status_type::TxStatus;
pub use tx_type_type::TxType;
pub use user_key_table::*;
pub use user_key_type::UserKey;
pub use user_pin_table::*;
pub use user_pin_type::UserPin;
pub use user_preferences_table::*;
pub use user_preferences_type::UserPreferences;
pub use ussd_code_table::*;
pub use ussd_code_type::UssdCode;
pub use ussd_menu_item_type::UssdMenuItem;
pub use ussd_request_table::*;
pub use ussd_request_type::UssdRequest;
pub use ussd_response_table::*;
pub use ussd_response_type::UssdResponse;
pub use ussd_router_option_type::UssdRouterOption;
pub use ussd_screen_table::*;
pub use ussd_screen_type::UssdScreen;
pub use ussd_service_table::*;
pub use ussd_service_type::UssdService;
pub use ussd_session_table::*;
pub use ussd_session_type::UssdSession;
pub use withdrawal_request_table::*;
pub use withdrawal_request_type::WithdrawalRequest;
pub use withdrawal_status_type::WithdrawalStatus;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ClaimGatewayIdentity,
    ConfirmEthTx {
        eth_tx_id: u64,
        tx_hash: String,
        block_number: u64,
        gas_used: String,
    },
    FailEthTx {
        eth_tx_id: u64,
        tx_hash: Option<String>,
        reason: String,
    },
    IdentityConnected,
    IdentityDisconnected,
    LogSendEthTransaction {
        tx_hash: String,
        from_address: String,
        to_address: String,
        amount: String,
        phone_number: String,
        session_id: String,
    },
    LogSendEthTransactionWithFatf {
        tx_hash: String,
        from_address: String,
        to_address: String,
        amount: String,
        phone_number: String,
        session_id: String,
        originator_name: Option<String>,
        beneficiary_name: Option<String>,
        originator_country: Option<String>,
        beneficiary_country: Option<String>,
        originator_address: Option<String>,
        beneficiary_address: Option<String>,
        gas_fee: Option<String>,
        exchange_rate: Option<String>,
    },
    MapPhoneToWallet {
        phone_number: String,
        wallet_address: String,
        chain_id: u64,
        delegate_to: String,
        nonce: u64,
        v: u64,
        r: String,
        s: String,
    },
    MarkAuth7702Active {
        authority_address: String,
    },
    MarkEthTxBroadcast {
        eth_tx_id: u64,
        tx_hash: String,
    },
    MarkEthTxProcessing {
        eth_tx_id: u64,
        worker_id: String,
    },
    ProcessUssdStep {
        session_id: String,
        phone_number: String,
        network_code: String,
        service_code: String,
        text: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ClaimGatewayIdentity => "claim_gateway_identity",
            Reducer::ConfirmEthTx { .. } => "confirm_eth_tx",
            Reducer::FailEthTx { .. } => "fail_eth_tx",
            Reducer::IdentityConnected => "identity_connected",
            Reducer::IdentityDisconnected => "identity_disconnected",
            Reducer::LogSendEthTransaction { .. } => "log_send_eth_transaction",
            Reducer::LogSendEthTransactionWithFatf { .. } => "log_send_eth_transaction_with_fatf",
            Reducer::MapPhoneToWallet { .. } => "map_phone_to_wallet",
            Reducer::MarkAuth7702Active { .. } => "mark_auth7702_active",
            Reducer::MarkEthTxBroadcast { .. } => "mark_eth_tx_broadcast",
            Reducer::MarkEthTxProcessing { .. } => "mark_eth_tx_processing",
            Reducer::ProcessUssdStep { .. } => "process_ussd_step",
            _ => unreachable!(),
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "claim_gateway_identity" => Ok(__sdk::parse_reducer_args::<
                claim_gateway_identity_reducer::ClaimGatewayIdentityArgs,
            >("claim_gateway_identity", &value.args)?
            .into()),
            "confirm_eth_tx" => Ok(__sdk::parse_reducer_args::<
                confirm_eth_tx_reducer::ConfirmEthTxArgs,
            >("confirm_eth_tx", &value.args)?
            .into()),
            "fail_eth_tx" => Ok(
                __sdk::parse_reducer_args::<fail_eth_tx_reducer::FailEthTxArgs>(
                    "fail_eth_tx",
                    &value.args,
                )?
                .into(),
            ),
            "identity_connected" => Ok(__sdk::parse_reducer_args::<
                identity_connected_reducer::IdentityConnectedArgs,
            >("identity_connected", &value.args)?
            .into()),
            "identity_disconnected" => Ok(__sdk::parse_reducer_args::<
                identity_disconnected_reducer::IdentityDisconnectedArgs,
            >("identity_disconnected", &value.args)?
            .into()),
            "log_send_eth_transaction" => {
                Ok(__sdk::parse_reducer_args::<
                    log_send_eth_transaction_reducer::LogSendEthTransactionArgs,
                >("log_send_eth_transaction", &value.args)?
                .into())
            }
            "log_send_eth_transaction_with_fatf" => {
                Ok(__sdk::parse_reducer_args::<
                    log_send_eth_transaction_with_fatf_reducer::LogSendEthTransactionWithFatfArgs,
                >("log_send_eth_transaction_with_fatf", &value.args)?
                .into())
            }
            "map_phone_to_wallet" => Ok(__sdk::parse_reducer_args::<
                map_phone_to_wallet_reducer::MapPhoneToWalletArgs,
            >("map_phone_to_wallet", &value.args)?
            .into()),
            "mark_auth7702_active" => Ok(__sdk::parse_reducer_args::<
                mark_auth_7702_active_reducer::MarkAuth7702ActiveArgs,
            >("mark_auth7702_active", &value.args)?
            .into()),
            "mark_eth_tx_broadcast" => Ok(__sdk::parse_reducer_args::<
                mark_eth_tx_broadcast_reducer::MarkEthTxBroadcastArgs,
            >("mark_eth_tx_broadcast", &value.args)?
            .into()),
            "mark_eth_tx_processing" => Ok(__sdk::parse_reducer_args::<
                mark_eth_tx_processing_reducer::MarkEthTxProcessingArgs,
            >("mark_eth_tx_processing", &value.args)?
            .into()),
            "process_ussd_step" => Ok(__sdk::parse_reducer_args::<
                process_ussd_step_reducer::ProcessUssdStepArgs,
            >("process_ussd_step", &value.args)?
            .into()),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    app_config: __sdk::TableUpdate<AppConfig>,
    auth_7702: __sdk::TableUpdate<Auth7702>,
    balance_query: __sdk::TableUpdate<BalanceQuery>,
    esim_profile: __sdk::TableUpdate<EsimProfile>,
    eth_audit_logs: __sdk::TableUpdate<EthAuditLog>,
    eth_tx: __sdk::TableUpdate<EthTx>,
    menu_item: __sdk::TableUpdate<UssdMenuItem>,
    router_option: __sdk::TableUpdate<UssdRouterOption>,
    sms_notification: __sdk::TableUpdate<SmsNotification>,
    user_key: __sdk::TableUpdate<UserKey>,
    user_pin: __sdk::TableUpdate<UserPin>,
    user_preferences: __sdk::TableUpdate<UserPreferences>,
    ussd_code: __sdk::TableUpdate<UssdCode>,
    ussd_request: __sdk::TableUpdate<UssdRequest>,
    ussd_response: __sdk::TableUpdate<UssdResponse>,
    ussd_screen: __sdk::TableUpdate<UssdScreen>,
    ussd_service: __sdk::TableUpdate<UssdService>,
    ussd_session: __sdk::TableUpdate<UssdSession>,
    withdrawal_request: __sdk::TableUpdate<WithdrawalRequest>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "app_config" => db_update
                    .app_config
                    .append(app_config_table::parse_table_update(table_update)?),
                "auth_7702" => db_update
                    .auth_7702
                    .append(auth_7702_table::parse_table_update(table_update)?),
                "balance_query" => db_update
                    .balance_query
                    .append(balance_query_table::parse_table_update(table_update)?),
                "esim_profile" => db_update
                    .esim_profile
                    .append(esim_profile_table::parse_table_update(table_update)?),
                "eth_audit_logs" => db_update
                    .eth_audit_logs
                    .append(eth_audit_logs_table::parse_table_update(table_update)?),
                "eth_tx" => db_update
                    .eth_tx
                    .append(eth_tx_table::parse_table_update(table_update)?),
                "menu_item" => db_update
                    .menu_item
                    .append(menu_item_table::parse_table_update(table_update)?),
                "router_option" => db_update
                    .router_option
                    .append(router_option_table::parse_table_update(table_update)?),
                "sms_notification" => db_update
                    .sms_notification
                    .append(sms_notification_table::parse_table_update(table_update)?),
                "user_key" => db_update
                    .user_key
                    .append(user_key_table::parse_table_update(table_update)?),
                "user_pin" => db_update
                    .user_pin
                    .append(user_pin_table::parse_table_update(table_update)?),
                "user_preferences" => db_update
                    .user_preferences
                    .append(user_preferences_table::parse_table_update(table_update)?),
                "ussd_code" => db_update
                    .ussd_code
                    .append(ussd_code_table::parse_table_update(table_update)?),
                "ussd_request" => db_update
                    .ussd_request
                    .append(ussd_request_table::parse_table_update(table_update)?),
                "ussd_response" => db_update
                    .ussd_response
                    .append(ussd_response_table::parse_table_update(table_update)?),
                "ussd_screen" => db_update
                    .ussd_screen
                    .append(ussd_screen_table::parse_table_update(table_update)?),
                "ussd_service" => db_update
                    .ussd_service
                    .append(ussd_service_table::parse_table_update(table_update)?),
                "ussd_session" => db_update
                    .ussd_session
                    .append(ussd_session_table::parse_table_update(table_update)?),
                "withdrawal_request" => db_update
                    .withdrawal_request
                    .append(withdrawal_request_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.app_config = cache
            .apply_diff_to_table::<AppConfig>("app_config", &self.app_config)
            .with_updates_by_pk(|row| &row.key);
        diff.auth_7702 = cache
            .apply_diff_to_table::<Auth7702>("auth_7702", &self.auth_7702)
            .with_updates_by_pk(|row| &row.authority_address);
        diff.balance_query = cache
            .apply_diff_to_table::<BalanceQuery>("balance_query", &self.balance_query)
            .with_updates_by_pk(|row| &row.session_id);
        diff.esim_profile = cache
            .apply_diff_to_table::<EsimProfile>("esim_profile", &self.esim_profile)
            .with_updates_by_pk(|row| &row.phone_number);
        diff.eth_audit_logs = cache
            .apply_diff_to_table::<EthAuditLog>("eth_audit_logs", &self.eth_audit_logs)
            .with_updates_by_pk(|row| &row.id);
        diff.eth_tx = cache
            .apply_diff_to_table::<EthTx>("eth_tx", &self.eth_tx)
            .with_updates_by_pk(|row| &row.id);
        diff.menu_item = cache.apply_diff_to_table::<UssdMenuItem>("menu_item", &self.menu_item);
        diff.router_option =
            cache.apply_diff_to_table::<UssdRouterOption>("router_option", &self.router_option);
        diff.sms_notification = cache
            .apply_diff_to_table::<SmsNotification>("sms_notification", &self.sms_notification)
            .with_updates_by_pk(|row| &row.id);
        diff.user_key = cache
            .apply_diff_to_table::<UserKey>("user_key", &self.user_key)
            .with_updates_by_pk(|row| &row.phone_number);
        diff.user_pin = cache
            .apply_diff_to_table::<UserPin>("user_pin", &self.user_pin)
            .with_updates_by_pk(|row| &row.phone_number);
        diff.user_preferences = cache
            .apply_diff_to_table::<UserPreferences>("user_preferences", &self.user_preferences)
            .with_updates_by_pk(|row| &row.phone_number);
        diff.ussd_code = cache
            .apply_diff_to_table::<UssdCode>("ussd_code", &self.ussd_code)
            .with_updates_by_pk(|row| &row.id);
        diff.ussd_request = cache
            .apply_diff_to_table::<UssdRequest>("ussd_request", &self.ussd_request)
            .with_updates_by_pk(|row| &row.id);
        diff.ussd_response = cache
            .apply_diff_to_table::<UssdResponse>("ussd_response", &self.ussd_response)
            .with_updates_by_pk(|row| &row.session_id);
        diff.ussd_screen = cache
            .apply_diff_to_table::<UssdScreen>("ussd_screen", &self.ussd_screen)
            .with_updates_by_pk(|row| &row.id);
        diff.ussd_service = cache
            .apply_diff_to_table::<UssdService>("ussd_service", &self.ussd_service)
            .with_updates_by_pk(|row| &row.id);
        diff.ussd_session = cache
            .apply_diff_to_table::<UssdSession>("ussd_session", &self.ussd_session)
            .with_updates_by_pk(|row| &row.session_id);
        diff.withdrawal_request = cache
            .apply_diff_to_table::<WithdrawalRequest>(
                "withdrawal_request",
                &self.withdrawal_request,
            )
            .with_updates_by_pk(|row| &row.id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    app_config: __sdk::TableAppliedDiff<'r, AppConfig>,
    auth_7702: __sdk::TableAppliedDiff<'r, Auth7702>,
    balance_query: __sdk::TableAppliedDiff<'r, BalanceQuery>,
    esim_profile: __sdk::TableAppliedDiff<'r, EsimProfile>,
    eth_audit_logs: __sdk::TableAppliedDiff<'r, EthAuditLog>,
    eth_tx: __sdk::TableAppliedDiff<'r, EthTx>,
    menu_item: __sdk::TableAppliedDiff<'r, UssdMenuItem>,
    router_option: __sdk::TableAppliedDiff<'r, UssdRouterOption>,
    sms_notification: __sdk::TableAppliedDiff<'r, SmsNotification>,
    user_key: __sdk::TableAppliedDiff<'r, UserKey>,
    user_pin: __sdk::TableAppliedDiff<'r, UserPin>,
    user_preferences: __sdk::TableAppliedDiff<'r, UserPreferences>,
    ussd_code: __sdk::TableAppliedDiff<'r, UssdCode>,
    ussd_request: __sdk::TableAppliedDiff<'r, UssdRequest>,
    ussd_response: __sdk::TableAppliedDiff<'r, UssdResponse>,
    ussd_screen: __sdk::TableAppliedDiff<'r, UssdScreen>,
    ussd_service: __sdk::TableAppliedDiff<'r, UssdService>,
    ussd_session: __sdk::TableAppliedDiff<'r, UssdSession>,
    withdrawal_request: __sdk::TableAppliedDiff<'r, WithdrawalRequest>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AppConfig>("app_config", &self.app_config, event);
        callbacks.invoke_table_row_callbacks::<Auth7702>("auth_7702", &self.auth_7702, event);
        callbacks.invoke_table_row_callbacks::<BalanceQuery>(
            "balance_query",
            &self.balance_query,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EsimProfile>(
            "esim_profile",
            &self.esim_profile,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EthAuditLog>(
            "eth_audit_logs",
            &self.eth_audit_logs,
            event,
        );
        callbacks.invoke_table_row_callbacks::<EthTx>("eth_tx", &self.eth_tx, event);
        callbacks.invoke_table_row_callbacks::<UssdMenuItem>("menu_item", &self.menu_item, event);
        callbacks.invoke_table_row_callbacks::<UssdRouterOption>(
            "router_option",
            &self.router_option,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SmsNotification>(
            "sms_notification",
            &self.sms_notification,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UserKey>("user_key", &self.user_key, event);
        callbacks.invoke_table_row_callbacks::<UserPin>("user_pin", &self.user_pin, event);
        callbacks.invoke_table_row_callbacks::<UserPreferences>(
            "user_preferences",
            &self.user_preferences,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UssdCode>("ussd_code", &self.ussd_code, event);
        callbacks.invoke_table_row_callbacks::<UssdRequest>(
            "ussd_request",
            &self.ussd_request,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UssdResponse>(
            "ussd_response",
            &self.ussd_response,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UssdScreen>("ussd_screen", &self.ussd_screen, event);
        callbacks.invoke_table_row_callbacks::<UssdService>(
            "ussd_service",
            &self.ussd_service,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UssdSession>(
            "ussd_session",
            &self.ussd_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WithdrawalRequest>(
            "withdrawal_request",
            &self.withdrawal_request,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        app_config_table::register_table(client_cache);
        auth_7702_table::register_table(client_cache);
        balance_query_table::register_table(client_cache);
        esim_profile_table::register_table(client_cache);
        eth_audit_logs_table::register_table(client_cache);
        eth_tx_table::register_table(client_cache);
        menu_item_table::register_table(client_cache);
        router_option_table::register_table(client_cache);
        sms_notification_table::register_table(client_cache);
        user_key_table::register_table(client_cache);
        user_pin_table::register_table(client_cache);
        user_preferences_table::register_table(client_cache);
        ussd_code_table::register_table(client_cache);
        ussd_request_table::register_table(client_cache);
        ussd_response_table::register_table(client_cache);
        ussd_screen_table::register_table(client_cache);
        ussd_service_table::register_table(client_cache);
        ussd_session_table::register_table(client_cache);
        withdrawal_request_table::register_table(client_cache);
    }
}
