// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProcessUssdStepArgs {
    pub session_id: String,
    pub phone_number: String,
    pub network_code: String,
    pub service_code: String,
    pub text: String,
}

impl From<ProcessUssdStepArgs> for super::Reducer {
    fn from(args: ProcessUssdStepArgs) -> Self {
        Self::ProcessUssdStep {
            session_id: args.session_id,
            phone_number: args.phone_number,
            network_code: args.network_code,
            service_code: args.service_code,
            text: args.text,
        }
    }
}

impl __sdk::InModule for ProcessUssdStepArgs {
    type Module = super::RemoteModule;
}

pub struct ProcessUssdStepCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `process_ussd_step`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait process_ussd_step {
    /// Request that the remote module invoke the reducer `process_ussd_step` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_process_ussd_step`] callbacks.
    fn process_ussd_step(
        &self,
        session_id: String,
        phone_number: String,
        network_code: String,
        service_code: String,
        text: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `process_ussd_step`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ProcessUssdStepCallbackId`] can be passed to [`Self::remove_on_process_ussd_step`]
    /// to cancel the callback.
    fn on_process_ussd_step(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &String)
            + Send
            + 'static,
    ) -> ProcessUssdStepCallbackId;
    /// Cancel a callback previously registered by [`Self::on_process_ussd_step`],
    /// causing it not to run in the future.
    fn remove_on_process_ussd_step(&self, callback: ProcessUssdStepCallbackId);
}

impl process_ussd_step for super::RemoteReducers {
    fn process_ussd_step(
        &self,
        session_id: String,
        phone_number: String,
        network_code: String,
        service_code: String,
        text: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "process_ussd_step",
            ProcessUssdStepArgs {
                session_id,
                phone_number,
                network_code,
                service_code,
                text,
            },
        )
    }
    fn on_process_ussd_step(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &String, &String)
            + Send
            + 'static,
    ) -> ProcessUssdStepCallbackId {
        ProcessUssdStepCallbackId(self.imp.on_reducer(
            "process_ussd_step",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ProcessUssdStep {
                                    session_id,
                                    phone_number,
                                    network_code,
                                    service_code,
                                    text,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    session_id,
                    phone_number,
                    network_code,
                    service_code,
                    text,
                )
            }),
        ))
    }
    fn remove_on_process_ussd_step(&self, callback: ProcessUssdStepCallbackId) {
        self.imp.remove_on_reducer("process_ussd_step", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `process_ussd_step`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_process_ussd_step {
    /// Set the call-reducer flags for the reducer `process_ussd_step` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn process_ussd_step(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_process_ussd_step for super::SetReducerFlags {
    fn process_ussd_step(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("process_ussd_step", flags);
    }
}
