// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ussd_router_option_type::UssdRouterOption;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `router_option`.
///
/// Obtain a handle from the [`RouterOptionTableAccess::router_option`] method on [`super::RemoteTables`],
/// like `ctx.db.router_option()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.router_option().on_insert(...)`.
pub struct RouterOptionTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdRouterOption>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `router_option`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RouterOptionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RouterOptionTableHandle`], which mediates access to the table `router_option`.
    fn router_option(&self) -> RouterOptionTableHandle<'_>;
}

impl RouterOptionTableAccess for super::RemoteTables {
    fn router_option(&self) -> RouterOptionTableHandle<'_> {
        RouterOptionTableHandle {
            imp: self.imp.get_table::<UssdRouterOption>("router_option"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RouterOptionInsertCallbackId(__sdk::CallbackId);
pub struct RouterOptionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RouterOptionTableHandle<'ctx> {
    type Row = UssdRouterOption;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdRouterOption> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RouterOptionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RouterOptionInsertCallbackId {
        RouterOptionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RouterOptionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RouterOptionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RouterOptionDeleteCallbackId {
        RouterOptionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RouterOptionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdRouterOption>("router_option");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdRouterOption>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdRouterOption>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
