// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sms_notification_type::SmsNotification;
use super::sms_status_type::SmsStatus;
use super::sms_template_type::SmsTemplate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sms_notification`.
///
/// Obtain a handle from the [`SmsNotificationTableAccess::sms_notification`] method on [`super::RemoteTables`],
/// like `ctx.db.sms_notification()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sms_notification().on_insert(...)`.
pub struct SmsNotificationTableHandle<'ctx> {
    imp: __sdk::TableHandle<SmsNotification>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sms_notification`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SmsNotificationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SmsNotificationTableHandle`], which mediates access to the table `sms_notification`.
    fn sms_notification(&self) -> SmsNotificationTableHandle<'_>;
}

impl SmsNotificationTableAccess for super::RemoteTables {
    fn sms_notification(&self) -> SmsNotificationTableHandle<'_> {
        SmsNotificationTableHandle {
            imp: self.imp.get_table::<SmsNotification>("sms_notification"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SmsNotificationInsertCallbackId(__sdk::CallbackId);
pub struct SmsNotificationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SmsNotificationTableHandle<'ctx> {
    type Row = SmsNotification;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SmsNotification> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SmsNotificationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SmsNotificationInsertCallbackId {
        SmsNotificationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SmsNotificationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SmsNotificationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SmsNotificationDeleteCallbackId {
        SmsNotificationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SmsNotificationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SmsNotification>("sms_notification");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SmsNotificationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SmsNotificationTableHandle<'ctx> {
    type UpdateCallbackId = SmsNotificationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SmsNotificationUpdateCallbackId {
        SmsNotificationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SmsNotificationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SmsNotification>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SmsNotification>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `sms_notification`,
/// which allows point queries on the field of the same name
/// via the [`SmsNotificationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sms_notification().id().find(...)`.
pub struct SmsNotificationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SmsNotification, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SmsNotificationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sms_notification`.
    pub fn id(&self) -> SmsNotificationIdUnique<'ctx> {
        SmsNotificationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SmsNotificationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SmsNotification> {
        self.imp.find(col_val)
    }
}
