// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sms_status_type::SmsStatus;
use super::sms_template_type::SmsTemplate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SmsNotification {
    pub id: u64,
    pub phone_number: String,
    pub template: SmsTemplate,
    pub payload_json: String,
    pub status: SmsStatus,
    pub message_id: Option<String>,
    pub error_reason: Option<String>,
    pub processing_by: Option<String>,
    pub processing_since: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SmsNotification {
    type Module = super::RemoteModule;
}
