// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_key_type::UserKey;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_key`.
///
/// Obtain a handle from the [`UserKeyTableAccess::user_key`] method on [`super::RemoteTables`],
/// like `ctx.db.user_key()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_key().on_insert(...)`.
pub struct UserKeyTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserKey>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_key`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserKeyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserKeyTableHandle`], which mediates access to the table `user_key`.
    fn user_key(&self) -> UserKeyTableHandle<'_>;
}

impl UserKeyTableAccess for super::RemoteTables {
    fn user_key(&self) -> UserKeyTableHandle<'_> {
        UserKeyTableHandle {
            imp: self.imp.get_table::<UserKey>("user_key"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserKeyInsertCallbackId(__sdk::CallbackId);
pub struct UserKeyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserKeyTableHandle<'ctx> {
    type Row = UserKey;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserKey> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserKeyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserKeyInsertCallbackId {
        UserKeyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserKeyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserKeyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserKeyDeleteCallbackId {
        UserKeyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserKeyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserKey>("user_key");
    _table.add_unique_constraint::<String>("phone_number", |row| &row.phone_number);
}
pub struct UserKeyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserKeyTableHandle<'ctx> {
    type UpdateCallbackId = UserKeyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserKeyUpdateCallbackId {
        UserKeyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserKeyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserKey>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserKey>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `phone_number` unique index on the table `user_key`,
/// which allows point queries on the field of the same name
/// via the [`UserKeyPhoneNumberUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_key().phone_number().find(...)`.
pub struct UserKeyPhoneNumberUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserKey, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserKeyTableHandle<'ctx> {
    /// Get a handle on the `phone_number` unique index on the table `user_key`.
    pub fn phone_number(&self) -> UserKeyPhoneNumberUnique<'ctx> {
        UserKeyPhoneNumberUnique {
            imp: self.imp.get_unique_constraint::<String>("phone_number"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserKeyPhoneNumberUnique<'ctx> {
    /// Find the subscribed row whose `phone_number` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserKey> {
        self.imp.find(col_val)
    }
}
