// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserPreferences {
    pub phone_number: String,
    pub base_token: String,
    pub default_withdraw_method: Option<String>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for UserPreferences {
    type Module = super::RemoteModule;
}
