// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_preferences_type::UserPreferences;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_preferences`.
///
/// Obtain a handle from the [`UserPreferencesTableAccess::user_preferences`] method on [`super::RemoteTables`],
/// like `ctx.db.user_preferences()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_preferences().on_insert(...)`.
pub struct UserPreferencesTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserPreferences>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_preferences`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserPreferencesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserPreferencesTableHandle`], which mediates access to the table `user_preferences`.
    fn user_preferences(&self) -> UserPreferencesTableHandle<'_>;
}

impl UserPreferencesTableAccess for super::RemoteTables {
    fn user_preferences(&self) -> UserPreferencesTableHandle<'_> {
        UserPreferencesTableHandle {
            imp: self.imp.get_table::<UserPreferences>("user_preferences"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserPreferencesInsertCallbackId(__sdk::CallbackId);
pub struct UserPreferencesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserPreferencesTableHandle<'ctx> {
    type Row = UserPreferences;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserPreferences> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserPreferencesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserPreferencesInsertCallbackId {
        UserPreferencesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserPreferencesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserPreferencesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserPreferencesDeleteCallbackId {
        UserPreferencesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserPreferencesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserPreferences>("user_preferences");
    _table.add_unique_constraint::<String>("phone_number", |row| &row.phone_number);
}
pub struct UserPreferencesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserPreferencesTableHandle<'ctx> {
    type UpdateCallbackId = UserPreferencesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserPreferencesUpdateCallbackId {
        UserPreferencesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserPreferencesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserPreferences>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserPreferences>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `phone_number` unique index on the table `user_preferences`,
/// which allows point queries on the field of the same name
/// via the [`UserPreferencesPhoneNumberUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_preferences().phone_number().find(...)`.
pub struct UserPreferencesPhoneNumberUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserPreferences, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserPreferencesTableHandle<'ctx> {
    /// Get a handle on the `phone_number` unique index on the table `user_preferences`.
    pub fn phone_number(&self) -> UserPreferencesPhoneNumberUnique<'ctx> {
        UserPreferencesPhoneNumberUnique {
            imp: self.imp.get_unique_constraint::<String>("phone_number"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserPreferencesPhoneNumberUnique<'ctx> {
    /// Find the subscribed row whose `phone_number` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserPreferences> {
        self.imp.find(col_val)
    }
}
