// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserPin {
    pub phone_number: String,
    pub pin_hash: String,
    pub salt: String,
    pub attempts: u32,
    pub locked: bool,
    pub last_attempt_time: Option<__sdk::Timestamp>,
    pub lockout_until: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for UserPin {
    type Module = super::RemoteModule;
}
