// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_pin_type::UserPin;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_pin`.
///
/// Obtain a handle from the [`UserPinTableAccess::user_pin`] method on [`super::RemoteTables`],
/// like `ctx.db.user_pin()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_pin().on_insert(...)`.
pub struct UserPinTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserPin>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_pin`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserPinTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserPinTableHandle`], which mediates access to the table `user_pin`.
    fn user_pin(&self) -> UserPinTableHandle<'_>;
}

impl UserPinTableAccess for super::RemoteTables {
    fn user_pin(&self) -> UserPinTableHandle<'_> {
        UserPinTableHandle {
            imp: self.imp.get_table::<UserPin>("user_pin"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserPinInsertCallbackId(__sdk::CallbackId);
pub struct UserPinDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserPinTableHandle<'ctx> {
    type Row = UserPin;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserPin> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserPinInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserPinInsertCallbackId {
        UserPinInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserPinInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserPinDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserPinDeleteCallbackId {
        UserPinDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserPinDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserPin>("user_pin");
    _table.add_unique_constraint::<String>("phone_number", |row| &row.phone_number);
}
pub struct UserPinUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserPinTableHandle<'ctx> {
    type UpdateCallbackId = UserPinUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserPinUpdateCallbackId {
        UserPinUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserPinUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserPin>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserPin>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `phone_number` unique index on the table `user_pin`,
/// which allows point queries on the field of the same name
/// via the [`UserPinPhoneNumberUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_pin().phone_number().find(...)`.
pub struct UserPinPhoneNumberUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserPin, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserPinTableHandle<'ctx> {
    /// Get a handle on the `phone_number` unique index on the table `user_pin`.
    pub fn phone_number(&self) -> UserPinPhoneNumberUnique<'ctx> {
        UserPinPhoneNumberUnique {
            imp: self.imp.get_unique_constraint::<String>("phone_number"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserPinPhoneNumberUnique<'ctx> {
    /// Find the subscribed row whose `phone_number` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserPin> {
        self.imp.find(col_val)
    }
}
