// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ussd_code_type::UssdCode;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ussd_code`.
///
/// Obtain a handle from the [`UssdCodeTableAccess::ussd_code`] method on [`super::RemoteTables`],
/// like `ctx.db.ussd_code()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_code().on_insert(...)`.
pub struct UssdCodeTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdCode>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ussd_code`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UssdCodeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UssdCodeTableHandle`], which mediates access to the table `ussd_code`.
    fn ussd_code(&self) -> UssdCodeTableHandle<'_>;
}

impl UssdCodeTableAccess for super::RemoteTables {
    fn ussd_code(&self) -> UssdCodeTableHandle<'_> {
        UssdCodeTableHandle {
            imp: self.imp.get_table::<UssdCode>("ussd_code"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UssdCodeInsertCallbackId(__sdk::CallbackId);
pub struct UssdCodeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UssdCodeTableHandle<'ctx> {
    type Row = UssdCode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdCode> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UssdCodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdCodeInsertCallbackId {
        UssdCodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UssdCodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UssdCodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdCodeDeleteCallbackId {
        UssdCodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UssdCodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdCode>("ussd_code");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("service_code", |row| &row.service_code);
}
pub struct UssdCodeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UssdCodeTableHandle<'ctx> {
    type UpdateCallbackId = UssdCodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UssdCodeUpdateCallbackId {
        UssdCodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UssdCodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdCode>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdCode>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ussd_code`,
/// which allows point queries on the field of the same name
/// via the [`UssdCodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_code().id().find(...)`.
pub struct UssdCodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdCode, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdCodeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ussd_code`.
    pub fn id(&self) -> UssdCodeIdUnique<'ctx> {
        UssdCodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdCodeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UssdCode> {
        self.imp.find(col_val)
    }
}

/// Access to the `service_code` unique index on the table `ussd_code`,
/// which allows point queries on the field of the same name
/// via the [`UssdCodeServiceCodeUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_code().service_code().find(...)`.
pub struct UssdCodeServiceCodeUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdCode, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdCodeTableHandle<'ctx> {
    /// Get a handle on the `service_code` unique index on the table `ussd_code`.
    pub fn service_code(&self) -> UssdCodeServiceCodeUnique<'ctx> {
        UssdCodeServiceCodeUnique {
            imp: self.imp.get_unique_constraint::<String>("service_code"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdCodeServiceCodeUnique<'ctx> {
    /// Find the subscribed row whose `service_code` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UssdCode> {
        self.imp.find(col_val)
    }
}
