// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UssdSession {
    pub session_id: String,
    pub phone_number: String,
    pub network_code: String,
    pub service_code: String,
    pub data: String,
    pub current_screen: String,
    pub response_text: Option<String>,
    pub error_text: Option<String>,
    pub last_interaction_time: __sdk::Timestamp,
    pub client: __sdk::Identity,
}

impl __sdk::InModule for UssdSession {
    type Module = super::RemoteModule;
}
