// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UssdRequest {
    pub id: u64,
    pub ussd_menu: u64,
    pub session_id: String,
    pub raw_data: String,
    pub status: String,
    pub created_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for UssdRequest {
    type Module = super::RemoteModule;
}
