// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ussd_response_type::UssdResponse;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ussd_response`.
///
/// Obtain a handle from the [`UssdResponseTableAccess::ussd_response`] method on [`super::RemoteTables`],
/// like `ctx.db.ussd_response()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_response().on_insert(...)`.
pub struct UssdResponseTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdResponse>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ussd_response`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UssdResponseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UssdResponseTableHandle`], which mediates access to the table `ussd_response`.
    fn ussd_response(&self) -> UssdResponseTableHandle<'_>;
}

impl UssdResponseTableAccess for super::RemoteTables {
    fn ussd_response(&self) -> UssdResponseTableHandle<'_> {
        UssdResponseTableHandle {
            imp: self.imp.get_table::<UssdResponse>("ussd_response"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UssdResponseInsertCallbackId(__sdk::CallbackId);
pub struct UssdResponseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UssdResponseTableHandle<'ctx> {
    type Row = UssdResponse;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdResponse> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UssdResponseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdResponseInsertCallbackId {
        UssdResponseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UssdResponseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UssdResponseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdResponseDeleteCallbackId {
        UssdResponseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UssdResponseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdResponse>("ussd_response");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}
pub struct UssdResponseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UssdResponseTableHandle<'ctx> {
    type UpdateCallbackId = UssdResponseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UssdResponseUpdateCallbackId {
        UssdResponseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UssdResponseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdResponse>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdResponse>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `session_id` unique index on the table `ussd_response`,
/// which allows point queries on the field of the same name
/// via the [`UssdResponseSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_response().session_id().find(...)`.
pub struct UssdResponseSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdResponse, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdResponseTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `ussd_response`.
    pub fn session_id(&self) -> UssdResponseSessionIdUnique<'ctx> {
        UssdResponseSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdResponseSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UssdResponse> {
        self.imp.find(col_val)
    }
}
