// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::screen_type_type::ScreenType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UssdScreen {
    pub id: u64,
    pub name: String,
    pub screen_type: ScreenType,
    pub default_next_screen: String,
    pub ussd_code: u64,
    pub text: String,
    pub function: Option<String>,
}

impl __sdk::InModule for UssdScreen {
    type Module = super::RemoteModule;
}
