// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ussd_session_type::UssdSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ussd_session`.
///
/// Obtain a handle from the [`UssdSessionTableAccess::ussd_session`] method on [`super::RemoteTables`],
/// like `ctx.db.ussd_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_session().on_insert(...)`.
pub struct UssdSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ussd_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UssdSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UssdSessionTableHandle`], which mediates access to the table `ussd_session`.
    fn ussd_session(&self) -> UssdSessionTableHandle<'_>;
}

impl UssdSessionTableAccess for super::RemoteTables {
    fn ussd_session(&self) -> UssdSessionTableHandle<'_> {
        UssdSessionTableHandle {
            imp: self.imp.get_table::<UssdSession>("ussd_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UssdSessionInsertCallbackId(__sdk::CallbackId);
pub struct UssdSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UssdSessionTableHandle<'ctx> {
    type Row = UssdSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UssdSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdSessionInsertCallbackId {
        UssdSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UssdSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UssdSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdSessionDeleteCallbackId {
        UssdSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UssdSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdSession>("ussd_session");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}
pub struct UssdSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UssdSessionTableHandle<'ctx> {
    type UpdateCallbackId = UssdSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UssdSessionUpdateCallbackId {
        UssdSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UssdSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `session_id` unique index on the table `ussd_session`,
/// which allows point queries on the field of the same name
/// via the [`UssdSessionSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_session().session_id().find(...)`.
pub struct UssdSessionSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdSession, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdSessionTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `ussd_session`.
    pub fn session_id(&self) -> UssdSessionSessionIdUnique<'ctx> {
        UssdSessionSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdSessionSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UssdSession> {
        self.imp.find(col_val)
    }
}
