// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ussd_request_type::UssdRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ussd_request`.
///
/// Obtain a handle from the [`UssdRequestTableAccess::ussd_request`] method on [`super::RemoteTables`],
/// like `ctx.db.ussd_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_request().on_insert(...)`.
pub struct UssdRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ussd_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UssdRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UssdRequestTableHandle`], which mediates access to the table `ussd_request`.
    fn ussd_request(&self) -> UssdRequestTableHandle<'_>;
}

impl UssdRequestTableAccess for super::RemoteTables {
    fn ussd_request(&self) -> UssdRequestTableHandle<'_> {
        UssdRequestTableHandle {
            imp: self.imp.get_table::<UssdRequest>("ussd_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UssdRequestInsertCallbackId(__sdk::CallbackId);
pub struct UssdRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UssdRequestTableHandle<'ctx> {
    type Row = UssdRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UssdRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdRequestInsertCallbackId {
        UssdRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UssdRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UssdRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdRequestDeleteCallbackId {
        UssdRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UssdRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdRequest>("ussd_request");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct UssdRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UssdRequestTableHandle<'ctx> {
    type UpdateCallbackId = UssdRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UssdRequestUpdateCallbackId {
        UssdRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UssdRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ussd_request`,
/// which allows point queries on the field of the same name
/// via the [`UssdRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_request().id().find(...)`.
pub struct UssdRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ussd_request`.
    pub fn id(&self) -> UssdRequestIdUnique<'ctx> {
        UssdRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UssdRequest> {
        self.imp.find(col_val)
    }
}
