// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ussd_service_type::UssdService;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ussd_service`.
///
/// Obtain a handle from the [`UssdServiceTableAccess::ussd_service`] method on [`super::RemoteTables`],
/// like `ctx.db.ussd_service()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_service().on_insert(...)`.
pub struct UssdServiceTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdService>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ussd_service`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UssdServiceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UssdServiceTableHandle`], which mediates access to the table `ussd_service`.
    fn ussd_service(&self) -> UssdServiceTableHandle<'_>;
}

impl UssdServiceTableAccess for super::RemoteTables {
    fn ussd_service(&self) -> UssdServiceTableHandle<'_> {
        UssdServiceTableHandle {
            imp: self.imp.get_table::<UssdService>("ussd_service"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UssdServiceInsertCallbackId(__sdk::CallbackId);
pub struct UssdServiceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UssdServiceTableHandle<'ctx> {
    type Row = UssdService;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdService> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UssdServiceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdServiceInsertCallbackId {
        UssdServiceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UssdServiceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UssdServiceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdServiceDeleteCallbackId {
        UssdServiceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UssdServiceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdService>("ussd_service");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct UssdServiceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UssdServiceTableHandle<'ctx> {
    type UpdateCallbackId = UssdServiceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UssdServiceUpdateCallbackId {
        UssdServiceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UssdServiceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdService>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdService>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ussd_service`,
/// which allows point queries on the field of the same name
/// via the [`UssdServiceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_service().id().find(...)`.
pub struct UssdServiceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdService, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdServiceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ussd_service`.
    pub fn id(&self) -> UssdServiceIdUnique<'ctx> {
        UssdServiceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdServiceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UssdService> {
        self.imp.find(col_val)
    }
}
