// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::screen_type_type::ScreenType;
use super::ussd_screen_type::UssdScreen;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ussd_screen`.
///
/// Obtain a handle from the [`UssdScreenTableAccess::ussd_screen`] method on [`super::RemoteTables`],
/// like `ctx.db.ussd_screen()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_screen().on_insert(...)`.
pub struct UssdScreenTableHandle<'ctx> {
    imp: __sdk::TableHandle<UssdScreen>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ussd_screen`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UssdScreenTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UssdScreenTableHandle`], which mediates access to the table `ussd_screen`.
    fn ussd_screen(&self) -> UssdScreenTableHandle<'_>;
}

impl UssdScreenTableAccess for super::RemoteTables {
    fn ussd_screen(&self) -> UssdScreenTableHandle<'_> {
        UssdScreenTableHandle {
            imp: self.imp.get_table::<UssdScreen>("ussd_screen"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UssdScreenInsertCallbackId(__sdk::CallbackId);
pub struct UssdScreenDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UssdScreenTableHandle<'ctx> {
    type Row = UssdScreen;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UssdScreen> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UssdScreenInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdScreenInsertCallbackId {
        UssdScreenInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UssdScreenInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UssdScreenDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UssdScreenDeleteCallbackId {
        UssdScreenDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UssdScreenDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UssdScreen>("ussd_screen");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct UssdScreenUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UssdScreenTableHandle<'ctx> {
    type UpdateCallbackId = UssdScreenUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UssdScreenUpdateCallbackId {
        UssdScreenUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UssdScreenUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UssdScreen>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UssdScreen>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `ussd_screen`,
/// which allows point queries on the field of the same name
/// via the [`UssdScreenIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_screen().id().find(...)`.
pub struct UssdScreenIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdScreen, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdScreenTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ussd_screen`.
    pub fn id(&self) -> UssdScreenIdUnique<'ctx> {
        UssdScreenIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdScreenIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UssdScreen> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `ussd_screen`,
/// which allows point queries on the field of the same name
/// via the [`UssdScreenNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ussd_screen().name().find(...)`.
pub struct UssdScreenNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UssdScreen, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UssdScreenTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `ussd_screen`.
    pub fn name(&self) -> UssdScreenNameUnique<'ctx> {
        UssdScreenNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UssdScreenNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UssdScreen> {
        self.imp.find(col_val)
    }
}
