// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::withdrawal_status_type::WithdrawalStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WithdrawalRequest {
    pub id: u64,
    pub phone_number: String,
    pub fiat_amount: String,
    pub currency: String,
    pub escrow_eth_tx_id: u64,
    pub refund_eth_tx_id: Option<u64>,
    pub pretium_ref: Option<String>,
    pub status: WithdrawalStatus,
    pub error_reason: Option<String>,
    pub processing_by: Option<String>,
    pub processing_since: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for WithdrawalRequest {
    type Module = super::RemoteModule;
}
