// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::withdrawal_request_type::WithdrawalRequest;
use super::withdrawal_status_type::WithdrawalStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `withdrawal_request`.
///
/// Obtain a handle from the [`WithdrawalRequestTableAccess::withdrawal_request`] method on [`super::RemoteTables`],
/// like `ctx.db.withdrawal_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.withdrawal_request().on_insert(...)`.
pub struct WithdrawalRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<WithdrawalRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `withdrawal_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WithdrawalRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WithdrawalRequestTableHandle`], which mediates access to the table `withdrawal_request`.
    fn withdrawal_request(&self) -> WithdrawalRequestTableHandle<'_>;
}

impl WithdrawalRequestTableAccess for super::RemoteTables {
    fn withdrawal_request(&self) -> WithdrawalRequestTableHandle<'_> {
        WithdrawalRequestTableHandle {
            imp: self
                .imp
                .get_table::<WithdrawalRequest>("withdrawal_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WithdrawalRequestInsertCallbackId(__sdk::CallbackId);
pub struct WithdrawalRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WithdrawalRequestTableHandle<'ctx> {
    type Row = WithdrawalRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WithdrawalRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WithdrawalRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WithdrawalRequestInsertCallbackId {
        WithdrawalRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WithdrawalRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WithdrawalRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WithdrawalRequestDeleteCallbackId {
        WithdrawalRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WithdrawalRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WithdrawalRequest>("withdrawal_request");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct WithdrawalRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WithdrawalRequestTableHandle<'ctx> {
    type UpdateCallbackId = WithdrawalRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WithdrawalRequestUpdateCallbackId {
        WithdrawalRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WithdrawalRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WithdrawalRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WithdrawalRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `withdrawal_request`,
/// which allows point queries on the field of the same name
/// via the [`WithdrawalRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.withdrawal_request().id().find(...)`.
pub struct WithdrawalRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WithdrawalRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WithdrawalRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `withdrawal_request`.
    pub fn id(&self) -> WithdrawalRequestIdUnique<'ctx> {
        WithdrawalRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WithdrawalRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WithdrawalRequest> {
        self.imp.find(col_val)
    }
}
